CREATE TABLE `ErrorLog`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`id` VARCHAR(10) NOT NULL,
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	PRIMARY KEY(`id`)
);
ALTER TABLE `ErrorLog`
	ADD CONSTRAINT `be99eba1bca8bb385de391b4e8339e` UNIQUE KEY(`id`);
